name: Create GitHub Release

on:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get current version
      id: get_version
      run: |
        current_version=$(grep 'version:' idf_component.yml | awk '{print $2}' | tr -d '"')
        echo "::set-output name=current_version::$current_version"

    - name: Create GitHub Release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ steps.get_version.outputs.current_version }}
        release_name: "Release ${{ steps.get_version.outputs.current_version }}"
        body: "Release of version ${{ steps.get_version.outputs.current_version }}"
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
