name: Main Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  trigger-update-version:
    uses: ./.github/workflows/update_version.yml
  trigger-update-version2:
    uses: ./.github/workflows/update_version.yml