name: Main Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  trigger-update-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name:  Trigger Update Version Workflow 
      uses: ./.github/workflows/release_helper/update_version.yml
    

  # trigger-publish-idf:
  #   runs-on: ubuntu-latest
  #   needs: trigger-update-version
  #   steps:
  #   - name: Trigger Publish to IDF Workflow
  #     run: |
  #       curl -X POST \
  #         -H "Accept: application/vnd.github.v3+json" \
  #         -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
  #         https://api.github.com/repos/${{ github.repository }}/actions/workflows/publish_idf.yml/dispatches \
  #         -d '{"ref":"main"}'

  # trigger-create-release:
  #   runs-on: ubuntu-latest
  #   needs: trigger-publish-idf
  #   steps:
  #   - name: Trigger Create Release Workflow
  #     run: |
  #       curl -X POST \
  #         -H "Accept: application/vnd.github.v3+json" \
  #         -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
  #         https://api.github.com/repos/${{ github.repository }}/actions/workflows/create_release.yml/dispatches \
  #         -d '{"ref":"main"}'